rf: 0.045
n_simulations: 10000
horizon_years: 44
milestones:
  - name: House
    year: 10
  - name: Retire
    year: 44
milestone_targets:
  - 3.0
  - 10.0

portfolios:
  - title: Current
    assets: [MSFT, DE, BP, BRK.B, VOO, QQQ, VXUS]
    weights: [0.1568, 0.1481, 0.1012, 0.06539, 0.1341, 0.04011, 0.0801]

  - title: VANGUARD
    assets: [VTI, VOO, VB, VXUS, VEA, VWO, VTV, VBR]
    weights: [0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125]
    rebalance_cost: 0.06

  - title: AVGE+OPINION
    assets: [AVGE, MSFT, DE, BP, BRK.B, TSM]
    weights: [0.9, 0.02, 0.02, 0.02, 0.02, 0.02]
    rebalance_cost: 0.06

  - title: AVGE
    assets: [AVGE]
    weights: [1.0]
    rebalance_cost: 0.06

  - title: DFAW
    assets: [DFAW]
    weights: [1.0]
    rebalance_cost: 0.06
